services:
  postgres:
    container_name: wos-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
  
  opencanary:
    container_name: wos-opencanary
    restart: unless-stopped
    image: thinkst/opencanary:0.9.6
    ports:
      # Comment/un-comment the port lines below to disable/enable the services you are using
      # FTP
      - "21:21"
      # SSH
      - "22:22"
      # Telnet
      # - "23:23"
      # TFTP
      # - "69:69"
      # HTTP
      - "80:80"
      # NTP
      # - "123:123"
      # SNMP
      # - "161:161"
      # MSSQL
      # - "1433:1433"
      # MYSQL
      # - "3306:3306"
      # RDP
      # - "3389:3389"
      # VNC
      # - "5000:5000"
      # SIP
      # - "5060:5060"
      # REDIS
      # - "6379:6379"
      # TCP Banner
      # - "8001:8001"
      # HTTP Proxy
      # - "8080:8080"
      # Git
      # - "9418:9418"
    volumes:
      - ./opencanary.conf:/root/.opencanary.conf
  
  app:
    container_name: wos-frontend
    image: shrunbr/wall-of-shame:0.1.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - opencanary
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    depends_on:
      - app

volumes:
  postgres-data: